version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: weekly
    time: "04:00"
  open-pull-requests-limit: 10
  versioning-strategy: increase
  ignore:
  - dependency-name: y18n
    versions:
    - 4.0.1
  - dependency-name: ember-source
    versions:
    - 3.24.1
    - 3.25.1
    - 3.25.3
  - dependency-name: ember-cli
    versions:
    - 3.24.0
    - 3.25.0
    - 3.25.2
  - dependency-name: eslint-plugin-ember
    versions:
    - 10.0.2
    - 10.2.0
  - dependency-name: ember-router-scroll
    versions:
    - 4.0.0
  - dependency-name: sass
    versions:
    - 1.32.0
  - dependency-name: ember-prism
    versions:
    - 0.9.0
  - dependency-name: lodash
    versions:
    - 4.17.20
  - dependency-name: elliptic
    versions:
    - 6.5.3
  - dependency-name: handlebars
    versions:
    - 4.7.6
  - dependency-name: jquery
    versions:
    - 3.5.1
  commit-message:
    prefix: ""
